//! Defines a simple text writer for the simulation data. This is a basic
//! implementation used only to verify the capacity of the program to write
//! output files and is deprecated for future use.

use crate::{OutputWriter, Simulation};
use std::io::{BufWriter, Error, ErrorKind, Write};

/// A simple text writer for the simulation data.
#[derive(Default)]
pub struct YamlWriter {
    pub frame_number: usize,
}

impl OutputWriter for YamlWriter {
    fn next_frame_number(&mut self) -> usize {
        self.frame_number += 1;
        self.frame_number
    }

    fn write_frame(
        &mut self,
        writer: &mut BufWriter<std::fs::File>,
        state: &dyn Simulation,
    ) -> std::io::Result<()> {
        writeln!(
            writer,
            "# Generated by MolSim. This output format can be re-inserted into the program.\n"
        )?;

        // let result = serde_yaml::to_writer(writer, state);
        // result.map_err(|e| Error::new(ErrorKind::InvalidData, e))

        // the problem was that `impl Serialization for dyn Trait` assumes static lifetime
        // https://stackoverflow.com/a/78637718
        let parsed =
            serde_yaml::to_string(state).map_err(|e| Error::new(ErrorKind::InvalidData, e))?;
        writeln!(writer, "{}", parsed)?;

        Ok(())
    }

    fn extension(&self) -> &str {
        "yml"
    }
}
